#!/bin/bash

set -e

forge_dir=$(cd `dirname $0` && cd .. && pwd)
vagrant_dir=$forge_dir/vagrant

$forge_dir/bosh/setup $vagrant_dir/assets
$forge_dir/bosh/build $vagrant_dir/assets

pushd "$vagrant_dir" >/dev/null
  packer build $@ forge.json
popd >/dev/null
