#!/bin/bash

set -e

if [[ -z $1 ]] || [[ -z $2 ]] || [[ -z $3 ]] || [[ ! -d $(dirname "$1") ]] || [[ ! -d $(dirname "$3") ]]; then
  >&2 echo "Usage:"
  >&2 echo -e "\t$0 /path/to/release release-name destination"
  exit 1
fi

release_path=$1
release_name=$2
destination=$3

pushd "$release_path" >/dev/null
  [[ -f Gemfile ]] && gem install bundler && bundle install || true
  yes yes | bosh -n reset release
  bosh -n create release --name "$release_name" --version 0 --with-tarball --force
  mv "dev_releases/$release_name/${release_name}-0.tgz" "$destination"
popd >/dev/null
