#!/bin/bash

set -e

if [[ -z $1 ]] || [[ -z $2 ]] || [[ -z $3 ]] || [[ ! -d $(dirname "$1") ]] || [[ ! -d $(dirname "$2") ]]; then
  >&2 echo "Usage:"
  >&2 echo -e "\t$0 /path/to/pcfdev-workspace /path/to/release release"
  exit 1
fi

pcfdev_workspace_dir=$1
release_path=$2
release_name=$3
assets_dir="${pcfdev_workspace_dir}/images/output/assets"
releases_dir="${pcfdev_workspace_dir}/releases"

pushd "$release_path" >/dev/null
  [[ -f Gemfile ]] && gem install bundler && bundle install || true
  yes yes | bosh -n reset release
  bosh -n create release --name "$release_name" --version 0 --with-tarball --force
  mv "dev_releases/$release_name/${release_name}-0.tgz" "$assets_dir/releases/"
popd >/dev/null
