// Automatically generated by MockGen. DO NOT EDIT!
// Source: pcfdev/provisioner (interfaces: Cert)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Cert interface
type MockCert struct {
	ctrl     *gomock.Controller
	recorder *_MockCertRecorder
}

// Recorder for MockCert (not exported)
type _MockCertRecorder struct {
	mock *MockCert
}

func NewMockCert(ctrl *gomock.Controller) *MockCert {
	mock := &MockCert{ctrl: ctrl}
	mock.recorder = &_MockCertRecorder{mock}
	return mock
}

func (_m *MockCert) EXPECT() *_MockCertRecorder {
	return _m.recorder
}

func (_m *MockCert) GenerateCert(_param0 string) ([]byte, []byte, error) {
	ret := _m.ctrl.Call(_m, "GenerateCert", _param0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (_mr *_MockCertRecorder) GenerateCert(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GenerateCert", arg0)
}
