// Automatically generated by MockGen. DO NOT EDIT!
// Source: pcfdev/provisioner (interfaces: UI)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of UI interface
type MockUI struct {
	ctrl     *gomock.Controller
	recorder *_MockUIRecorder
}

// Recorder for MockUI (not exported)
type _MockUIRecorder struct {
	mock *MockUI
}

func NewMockUI(ctrl *gomock.Controller) *MockUI {
	mock := &MockUI{ctrl: ctrl}
	mock.recorder = &_MockUIRecorder{mock}
	return mock
}

func (_m *MockUI) EXPECT() *_MockUIRecorder {
	return _m.recorder
}

func (_m *MockUI) PrintHelpText(_param0 string) error {
	ret := _m.ctrl.Call(_m, "PrintHelpText", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockUIRecorder) PrintHelpText(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PrintHelpText", arg0)
}
