#!/bin/bash

if [[ -z $1 ]]; then
    >&2 echo "Usage:"
    >&2 echo -e "\t$0 <domain>"
    exit 1
fi

domain=$1

cat <<EOF
 _______  _______  _______    ______   _______  __   __
|       ||       ||       |  |      | |       ||  | |  |
|    _  ||       ||    ___|  |  _    ||    ___||  |_|  |
|   |_| ||       ||   |___   | | |   ||   |___ |       |
|    ___||      _||    ___|  | |_|   ||    ___||       |
|   |    |     |_ |   |      |       ||   |___  |     |
|___|    |_______||___|      |______| |_______|  |___|
EOF
echo "is now running."
echo "To begin using PCF Dev, please run:"
echo "    cf login -a https://api.$domain --skip-ssl-validation"
echo "Admin user => Email: admin / Password: admin"
echo "Regular user => Email: user / Password: pass"
