#!/bin/bash

set -e


exec 3>&1 4>&2 >>/var/pcfdev/reset.log 2>&1
set -x

source /var/pcfdev/common

if status runsvdir | grep -q 'start/running'; then
  wait_for_monit_to_start

  $monit stop all

  >&3 echo "Waiting for services to stop..."
  wait_for_services_to_stop

  stop runsvdir

  wait_for_monit_to_stop
fi

>&3 echo "Services stopped. Resetting data..."
rm -rf /var/vcap/nfs /var/vcap/data/{compile,tmp}

>&3 echo "Deleting stale state files not needed for mysql migrations"
find /var/vcap/store/* -maxdepth 0 ! -name "*.sql" | xargs rm -rf

set +x
exec 1>&3 2>&4
