#!/bin/bash

set -e

if [[ -z $1 ]]; then
    >&2 echo "Usage:"
    >&2 echo -e "\t$0 <domain>"
    exit 1
fi

exec 3>&1 4>&2 >>/var/pcfdev/provision.log 2>&1
set -x
source /var/pcfdev/common

domain=$1

>&3 echo "Waiting for services to start..."

move_monit_control_files
start runsvdir
wait_for_monit_to_start
start_services mariadb_ctrl galera-healthcheck

while ! nc -z 127.0.0.1 3306; do
  sleep 1
done

for script in /var/vcap/jobs/*/bin/pre-start; do
  $script
done
start_services consul_agent garden etcd uaa

while [[ ! /var/vcap/jobs/uaa/bin/dns_health_check ]]; do
  sleep 1
done

start_services bbs

start_remaining

total=$(total_services)

while started=$(started_service_count) && [[ $started -lt $total ]]; do
  counter=$(($counter + 1))
  [[ $(($counter % 60)) = 0 ]] && >&3 echo "$started out of $total running"
  sleep 1
done
>&3 echo "$total out of $total running"

while [[ $(cc_status_code "$domain") != 200 ]]; do
  sleep 1
done

for script in /var/vcap/jobs/*/bin/post-start
do
  $script
done
exec 1>&3 2>&4
