#!/bin/bash

set -ex

source /var/pcfdev/common

domain=$(cat /var/pcfdev/domain)
status_code=$(cc_status_code ${domain})
service_count=$(total_services)

if [[ ${status_code} == "200" && -f "/run/pcfdev-healthcheck" ]]
then
  echo -n 'ok'
  exit 0
fi

exit 1
