#!/bin/bash

set -e


exec 3>&1 4>&2 >>/var/micropcf/reset.log 2>&1

monit="/var/vcap/bosh/bin/monit"

total_services() { $monit summary | grep -E '^(Process|File|System)' | wc -l; }
stopped_services() { $monit summary | grep 'not monitored' | grep -v 'pending' | wc -l; }

while [[ $(total_services) = 0 ]]; do
  sleep 1
done

$monit stop all

>&3 echo "Waiting for services to stop..."
while [[ $(stopped_services) -lt $(total_services) ]]; do
  sleep 1
done

stop runsvdir || true

>&3 echo "Services stopped. Resetting data..."
rm -rf /var/vcap/{store/*,nfs} /var/vcap/data/{compile,tmp}

exec 1>&3 2>&4
