#!/bin/bash

set -e

if [[ -z $1 ]]; then
    >&2 echo "Usage:"
    >&2 echo -e "\t$0 <domain>"
    exit 1
fi

exec 3>&1 4>&2 >>/var/pcfdev/snapshot.log 2>&1
set -x

source /var/pcfdev/common

domain=$1

while [[ $(cc_status_code "$domain") != 200 ]]; do
  sleep 1
done

while [[ $(available_buildpacks) -lt 8 ]]; do
  sleep 1
done

pg_dump -h 127.0.0.1 -p 5524 -U vcap ccdb > /var/pcfdev/ccdb

set +x
exec 1>&3 2>&4
