#!/bin/bash

set -e

images_dir=$(cd `dirname $0` && cd .. && pwd)
output_dir=$images_dir/base/output
mkdir -p $output_dir

pushd $images_dir/bosh >/dev/null
  bundle install
  ./setup $output_dir/assets
  ./build $output_dir/assets
popd >/dev/null

cp -a $images_dir/common/* $output_dir/

pushd "$output_dir" >/dev/null
  packer build $@ $images_dir/micropcf.json
popd >/dev/null
