#!/bin/bash

set -e

pcfdev_dir=$(cd `dirname $0` && cd ../.. && pwd)
images_dir=$pcfdev_dir/images
output_dir=$images_dir/base/output
mkdir -p "$output_dir"

"$pcfdev_dir/bosh/setup-packer" "$output_dir/packer-bosh"

releases='diego cf garden-linux etcd'
if ! "$pcfdev_dir/bosh/retrieve" "$output_dir/assets" $releases; then
  "$pcfdev_dir/bosh/build" "$output_dir/assets" $releases
fi

cp -a "$images_dir"/{http,scripts} "$output_dir/"
spiff merge \
  "$images_dir/manifest.yml" \
  <(echo "properties: {build: $(git -C "$pcfdev_dir" rev-parse HEAD)}") \
  > "$output_dir/manifest.yml"

pushd "$output_dir" >/dev/null
  packer build $@ -var 'distro=base' "$images_dir/pcfdev.json"
popd >/dev/null
