#!/bin/bash

set -e

micropcf_dir=$(cd `dirname $0` && cd ../.. && pwd)
images_dir=$micropcf_dir/images
output_dir=$images_dir/base/output
mkdir -p $output_dir

$images_dir/bosh/setup $output_dir/packer-bosh

releases='diego garden-linux cf-routing etcd cf'
if ! $images_dir/bosh/retrieve $output_dir/assets $releases; then
  $images_dir/bosh/build $output_dir/assets $releases
fi

cp -a $images_dir/{run,http,manifest.yml} $output_dir/

pushd "$output_dir" >/dev/null
  packer build $@ $images_dir/micropcf.json
popd >/dev/null
