#!/bin/bash

set -e

pcfdev_dir=$(cd `dirname $0` && cd .. && pwd)
images_dir=$pcfdev_dir/images

output_dir=$images_dir/output
mkdir -p "$output_dir"
rm -rf "$output_dir"/output-*

"$pcfdev_dir/bosh/setup-packer" "$output_dir/packer-bosh"

releases='diego cf garden-linux etcd cf-mysql'
"$pcfdev_dir/bosh/clone-releases"
"$pcfdev_dir/bosh/build" "$output_dir/assets" $releases

cp -a "$images_dir"/{http,keys,scripts} "$output_dir/"
spiff merge \
  "$images_dir/manifest.yml" \
  <(echo "properties: {build: $(git -C "$pcfdev_dir" rev-parse HEAD)}") \
  > "$output_dir/manifest.yml"

pushd "$output_dir" >/dev/null
  packer build $@ -var 'distro=oss' "$images_dir/pcfdev.json"
popd >/dev/null
