#!/bin/bash

set -e

pcfdev_dir=$(cd `dirname $0` && cd .. && pwd)
images_dir=$pcfdev_dir/images
output_dir=$images_dir/output

rm -rf "$output_dir"
mkdir "$output_dir"

"$pcfdev_dir/bosh/setup-packer" "$output_dir/packer-bosh"
"$pcfdev_dir/bosh/fetch-assets" "$pcfdev_dir/versions.json" "$output_dir"

spiff merge \
  "$images_dir/manifest.yml" \
  <(echo "properties: {build: $(git -C "$pcfdev_dir" rev-parse HEAD)}") \
  > "$output_dir/manifest.yml"

pushd "$output_dir" >/dev/null
  packer build $@ -var 'distro=oss' "$images_dir/pcfdev.json"
popd >/dev/null
