#!/bin/bash

set -e

if [[ -z $1 ]] && [[ -t 1 ]]; then
    >&2 echo "Usage:"
    >&2 echo -e "\t$0 /path/to/forge.tgz [forge tgz version]"
    >&2 echo -e "\t$0 [forge tgz version] > /path/to/forge.tgz"
    exit 1
fi

if [[ -t 1 ]]; then
  forge_tgz=$1
  forge_tgz_version=$2
else
  forge_tgz="-"
  forge_tgz_version=$1
fi

forge_dir=$(cd `dirname $0` && cd .. && pwd)
diego_release_dir=$forge_dir/diego-release
ltc_dir=$forge_dir/src/github.com/cloudfoundry-incubator/ltc
receptor_dir=$forge_dir/src/github.com/cloudfoundry-incubator/receptor

forge_version=$(git -C "$forge_dir" rev-parse HEAD)
diego_release_version=$(git -C "$diego_release_dir" describe --tags --always)
ltc_version=$(git -C "$ltc_dir" describe --tags --always)
receptor_version=$(git -C "$receptor_dir" describe --tags --always)

tmp_dir=$(mktemp -d /tmp/forge.XXXXXX)

cp -a $forge_dir/release/install $tmp_dir/

export GOPATH=$forge_dir:$diego_release_dir
export GOOS=linux
export GOARCH=amd64

# Brain

cp -a $forge_dir/release/brain $tmp_dir/

brain_bin_dir=$tmp_dir/brain/usr/local/bin
brain_lighttpd_dir=$tmp_dir/brain/var/forge/lighttpd
brain_artifacts_dir=$tmp_dir/brain/var/forge/artifacts
brain_cell_helper_dir=$tmp_dir/brain/var/vcap/jobs/file_server/packages/cell-helpers
brain_versions_dir=$tmp_dir/brain/var/forge/versions
mkdir -p $brain_lighttpd_dir $brain_artifacts_dir $brain_bin_dir $brain_cell_helper_dir $brain_versions_dir

(
  export GOPATH=$forge_dir/src/github.com/docker/docker/vendor:$GOPATH
  flags="-X github.com/cloudfoundry-incubator/ltc/setup_cli.forgeVersion=$forge_version
         -X github.com/cloudfoundry-incubator/ltc/setup_cli.diegoVersion=$diego_release_version"

  go build -a -ldflags "$flags" -o $brain_artifacts_dir/linux/ltc github.com/cloudfoundry-incubator/ltc
  GOOS=darwin go build -a -ldflags "$flags" -o $brain_artifacts_dir/osx/ltc github.com/cloudfoundry-incubator/ltc
  GOOS=windows go build -a -ldflags "$flags" -o $brain_artifacts_dir/windows/ltc.exe github.com/cloudfoundry-incubator/ltc
)

go build -a -o $brain_bin_dir/receptor github.com/cloudfoundry-incubator/receptor/cmd/receptor

pushd $brain_cell_helper_dir >/dev/null
  go build -a github.com/cloudfoundry-incubator/ltc/cell-helpers/davtool
  go build -a github.com/cloudfoundry-incubator/ltc/cell-helpers/s3tool
  tar czf cell-helpers.tgz davtool s3tool
  rm -f davtool s3tool
popd >/dev/null

echo $ltc_version > $brain_versions_dir/LTC
echo $forge_version > $brain_versions_dir/FORGE
echo $receptor_version > $brain_versions_dir/RECEPTOR
echo $forge_tgz_version > $brain_versions_dir/FORGE_TGZ

# Cell

cell_bin_dir=$tmp_dir/cell/usr/local/bin
cell_versions_dir=$tmp_dir/cell/var/forge/versions
mkdir -p $cell_bin_dir $cell_versions_dir

go build -a -o $cell_bin_dir/tee2metron github.com/cloudfoundry-incubator/ltc/cell-helpers/tee2metron

echo $ltc_version > $cell_versions_dir/LTC
echo $forge_version > $cell_versions_dir/FORGE
echo $forge_tgz_version > $cell_versions_dir/FORGE_TGZ

# Output

tar -czf "$forge_tgz" -C "$tmp_dir" brain cell install

rm -rf "$tmp_dir"
