#!/bin/bash

set -e

if [[ -z $1 ]] && [[ -t 1 ]]; then
    >&2 echo "Usage:"
    >&2 echo -e "\t$0 /path/to/forge.tgz [forge tgz version]"
    >&2 echo -e "\t$0 [forge tgz version] > /path/to/forge.tgz"
    exit 1
fi

if [[ -t 1 ]]; then
  forge_tgz=$1
  forge_tgz_version=$2
else
  forge_tgz="-"
  forge_tgz_version=$1
fi

forge_dir=$(cd `dirname $0` && cd .. && pwd)
forge_version=$(git -C "$forge_dir" rev-parse HEAD)

tmp_dir=$(mktemp -d /tmp/forge.XXXXXX)
versions_dir=$tmp_dir/root/var/forge/versions
mkdir -p $versions_dir

cp $forge_dir/release/install $tmp_dir/

echo $forge_version > $versions_dir/FORGE
echo $forge_tgz_version > $versions_dir/FORGE_TGZ

tar -czf "$forge_tgz" -C "$tmp_dir" root install

rm -rf "$tmp_dir"
