#!/bin/bash

set -e

if [[ -z $1 ]] || [[ ! -d $(dirname "$1") ]]; then
  >&2 echo "Usage:"
  >&2 echo -e "\t$0 /path/to/assets [first-release] [second-release] ..."
  exit 1
fi


assets_dir=$(mkdir -p "$1" && cd "$1" && pwd)
micropcf_dir=$(cd `dirname $0` && cd ../.. && pwd)
releases=${@:2}

if ! $micropcf_dir/bin/asset-absence $releases && ! $micropcf_dir/bin/asset-status $releases; then
  >&2 echo "Assets are available but dirty."
  exit 1
fi

signature=$($micropcf_dir/bin/asset-signature $releases)
if [[ -z $signature ]]; then
  >&2 echo "Assets not available in cache."
  exit 1
fi

aws s3api get-object --bucket micropcf --key asset-cache/${signature}.tar >(tar -C "$assets_dir" -x)
