#!/bin/bash

set -e

if [[ -z $1 ]]; then
    >&2 echo "Usage:"
    >&2 echo -e "\t$0 /path/to/packer-bosh"
    exit 1
fi

packer_bosh=$(cd `dirname $1` && pwd)/$(basename $1)

micropcf_dir=$(cd `dirname $0` && cd ../.. && pwd)
bosh_gopath=$micropcf_dir/images/bosh
packer_bosh_dir=$bosh_gopath/src/github.com/cppforlife/packer-bosh

GOPATH=$packer_bosh_dir/Godeps/_workspace:$bosh_gopath \
  eval "go build -a -o $packer_bosh github.com/cppforlife/packer-bosh/main"

chmod +x $packer_bosh

if [[ -f $HOME/.packerconfig ]]; then
  packer_config=$(cat $HOME/.packerconfig)
  echo "Updating existing ~/.packerconfig to point to downloaded packer-bosh."
fi
filter='. + {"provisioners": (.provisioners + {"packer-bosh": "'$packer_bosh'"})}'
echo ${packer_config:-'{}'} | jq "$filter" >$HOME/.packerconfig

